config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :create ]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end
  
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="banner-container">
    <h1>Cocktails at home for lockdown!</h1>
    <p>Find a cocktail to forget about theses hard times and add your own.</p>
    <a class="btn-banner" href="/cocktails/new">
        <svg>
          <rect x="0" y="0" fill="none" width="100%" height="100%"/>
        </svg>
      Add your cocktail
    </a>
  </div>
</div>

<div class="container py-3 mb-5">
  <div class="row">
    <div class="col col-md-6 offset-md-3">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @cocktails.each_with_index do |cocktail, index| %>
            <div class="carousel-item <%= "active" if index == 0 %>">
              <div class="card">
                <div class="card-image">
                  <% if cocktail.photo.attached? %>
                    <%= cl_image_tag cocktail.photo.key, height: 300, width: 400, crop: :fill %>
                  <% else %>
                    <img height="300" width="400" src="https://images.unsplash.com/photo-1551538827-9c037cb4f32a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=701&q=80">
                  <% end %>
                </div>
                <div class="card-info p-3">
                  <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>   
      </div> 
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div>
  <div class="row">
    <div class="home">
      <%= link_to cocktails_path, class: "btn home-btn" do %>
        <i class="fas fa-angle-left"> HOME</i>
      <% end %>
    </div> 
  </div>
  <div class="form-container d-flex">
    <div class="form-infos">
      <h3>Add your cocktail</h3>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name, :required => false %>
        <%= f.input :photo, input_html: { class: 'd-none' }, label_html: { class: 'btn btn-light'}, label: 'Upload a photo' %>
        <hr>
        <%= f.submit "Add cocktail", class: 'btn btn-light mt-3' %>
      <% end %>
    </div>
    <div class="form-image">
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
  <div class="row m-0">

    <div class="col-12 col-lg-6 p-0">
      <div class="container-img">
        <% if @cocktail.photo.attached? %>
          <%= cl_image_tag @cocktail.photo.key %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1551538827-9c037cb4f32a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=701&q=80" class="w-100">
        <% end %>
        <%= link_to cocktails_path, class: "btn home-btn", id: "sticky" do %>
          <i class="fas fa-angle-left"> HOME</i>
        <% end %>
      </div>    
    </div>

    <div class="col-12 col-lg-6 p-0">
      <div class="container-infos m-5">
        <h2><%= @cocktail.name %></h2>
        <h4>INGREDIENTS</h4>
        <div class="ingredients-list mb-5">
          <ul class='list-unstyled border-left pl-2'>
            <% @cocktail.doses.each do |dose| %>
              <li><%= dose.description %> of <%= dose.ingredient.name %>  
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-window-close"></i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <h5>Feel free to update the recipe</h5>
        <%= simple_form_for [ @cocktail, @dose ] do |f| %>
          <%= f.input :description, :required => false %>
          <%= f.association :ingredient, :required => false, input_html: { class: 'select2' } %>
          <%= f.submit "Add a dose", class: 'btn btn-light' %>
        <% end %>    
      </div>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>